# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy front release app

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOKERHUB_USERNAME }}
          password: ${{ secrets.DOKERHUB_PASSWORD }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./front/
          file: ./front/Dockerfile.prod
          push: true
          tags: recdolserver/imgenie-front-release

      - name: google auth
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCE_SA_KEY }}"

      - name: set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: use gcloud cli
        run: "gcloud info"

      - name: gcp deploy
        run: |-
          gcloud compute instances update-container "${{ secrets.FRONT_RELEASE_GCE_INSTANCE }}" \
            --zone "${{ secrets.FRONT_RELEASE_GCE_INSTANCE_ZONE }}" \
            --container-image "docker.io/recdolserver/imgenie-front-release" \
            --container-env PORT=80,REACT_APP_BACKEND_HOST="${{ secrets.FRONT_RELEASE_ENV__REACT_APP_BACKEND_HOST }}"

      - name: gcp reset
        run: |-
          gcloud compute instances reset "${{ secrets.FRONT_RELEASE_GCE_INSTANCE }}" \
            --zone "${{ secrets.FRONT_RELEASE_GCE_INSTANCE_ZONE }}"
